if [[ -f $HOME/.bashrc ]]; then source $HOME/.bashrc; fi
if [[ -f $HOME/.bashrc.local ]]; then source $HOME/.bashrc.local; fi
eval "$(rbenv init -)"
test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"

export PATH="$HOME/.fastlane/bin:$PATH"

